# fly.toml app configuration file generated for grafana-fly-test on 2025-09-17T18:18:10Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'grafana-fly-test'
primary_region = 'bom'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
